# Generated by Django 3.1.1 on 2020-09-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['tree_id', 'lft']},
        ),
    ]
